provider:
  name: faas
  gateway: http://localhost:8080

functions:
  patreon-responder:
    lang: python
    handler: ./patreon-responder
    image: alexellis2/patreon-responder:0.1

    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - secrets.yml

