provider:
  name: faas

functions:
  patreon-responder:
    lang: python
    handler: ./patreon-responder
    image: alexellis2/patreon-responder:0.3.2

    environment:
      write_debug: true
      read_debug: true
    environment_file:
#      - secrets.example.yml
      - secrets.yml

